"""Read-only audit of frozen delayed/Shapley inputs, folds and reward artifacts."""

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import yaml

from algorithms.offline.shapley_redistribution import (
    conserved_rewards,
    segment_inputs,
    SegmentReturnModel,
    standardize,
)
from scripts.cql_delayed.common import digest, read, verify, write

def audit(delayed, campaign, prepared, fit, arm):
    base, protocol = verify(delayed), verify(campaign)
    reference = verify(prepared)
    expected_inputs = protocol.get("preparation_sha256",
                                   protocol.get("original_preparation_sha256"))
    if expected_inputs is None:
        raise ValueError("Missing predictor input provenance")
    for name, expected in expected_inputs.items():
        if digest(prepared / name) != expected:
            raise ValueError(f"Prepared input hash mismatch: {name}")
    for name in ["algorithms/offline/shapley_redistribution.py",
                 "scripts/cql_shapley/fit_redistribute.py"]:
        if reference["source_sha256"][name] != protocol["source_sha256"][name]:
            raise ValueError(f"Fitting source changed: {name}")
        if digest(Path(__file__).resolve().parents[2] / name) != (
                protocol["source_sha256"][name]):
            raise ValueError(f"Audit implementation differs from frozen source: {name}")
    algorithm = "algorithms/offline/cql.py"
    if base["source_sha256"][algorithm] != protocol["source_sha256"][algorithm]:
        raise ValueError("CQL algorithms differ")
    if base["source_sha256"]["scripts/cql_delayed/trainer.py"] != (
            protocol["source_sha256"]["scripts/cql_shapley/trainer.py"]):
        raise ValueError("Trainer construction differs")
    configs = []
    for root, p, selected in [(delayed, base, arm), (campaign, protocol, "shapley")]:
        spec = p["runs"][selected]
        for name, expected in spec["data_sha256"].items():
            if digest(root / selected / name) != expected:
                raise ValueError(f"Training data hash mismatch: {selected}/{name}")
        config = yaml.safe_load((root / "source" / spec["config"]).read_text())
        configs.append({k: v for k, v in config.items() if k not in {"name", "group"}})
    if configs[0] != configs[1]:
        raise ValueError("Scientific training configurations differ")
    with np.load(prepared / "predictor/input.npz") as artifact:
        if set(artifact.files) != {"features", "returns", "starts", "ends"}:
            raise ValueError("Unexpected predictor input fields")
        features, returns = artifact["features"], artifact["returns"]
        starts, ends = artifact["starts"], artifact["ends"]
    with np.load(delayed / arm / "dataset.npz") as a:
        delayed_data = {key: a[key] for key in a.files}
    with np.load(campaign / "shapley/dataset.npz") as b:
        redistributed = {key: b[key] for key in b.files}
    for key in delayed_data:
        if key != "rewards":
            np.testing.assert_array_equal(delayed_data[key], redistributed[key])
    end_indices = np.flatnonzero(delayed_data["terminals"])
    np.testing.assert_array_equal(ends, end_indices)
    np.testing.assert_array_equal(starts, np.r_[0, ends[:-1] + 1])
    if np.any(delayed_data["rewards"][delayed_data["terminals"] == 0]):
        raise ValueError("Delayed baseline contains nonterminal rewards")
    expected_features = np.concatenate(
        [delayed_data["observations"], delayed_data["actions"]], axis=1)
    np.testing.assert_array_equal(features.reshape(expected_features.shape),
                                  expected_features)
    # Float64 totals are the exact values before baseline float32 storage.
    np.testing.assert_array_equal(returns.astype(np.float32),
                                  delayed_data["rewards"][ends])
    splits = read(prepared / "predictor/folds.json")
    seen, fold_reports, prediction_errors = [], [], []
    with np.load(fit / "attribution.npz") as artifact:
        attributed = {key: artifact[key] for key in artifact.files}
    np.testing.assert_array_equal(attributed["returns"], returns)
    diagnostics = read(fit / "diagnostics.json")
    if [row["trajectory"] for row in diagnostics] != list(range(len(returns))):
        raise ValueError("Missing or duplicate attribution diagnostics")
    for split in splits:
        train, valid, held = [set(split[k]) for k in ["train", "validation", "held"]]
        if (train & valid or train & held or valid & held
                or train | valid | held != set(range(len(returns)))):
            raise ValueError("Fold leakage or incomplete coverage")
        seen.extend(held)
        directory = fit / f"fold_{split['fold']}"
        # Only load trusted checkpoints generated by this project.
        checkpoint = torch.load(directory / "model.pt", map_location="cpu",
                                weights_only=False)
        if checkpoint["split"] != split:
            raise ValueError("Checkpoint trained with a different split")
        if checkpoint["settings"] != protocol["attribution"]:
            raise ValueError("Predictor settings differ from protocol")
        normalized, stats = standardize(features, returns, split["train"])
        for key, value in stats.items():
            np.testing.assert_allclose(checkpoint["stats"][key], value,
                                       rtol=1e-12, atol=1e-12)
        epochs = [json.loads(line) for line in
                  (directory / "epochs.jsonl").read_text().splitlines()]
        best = min(epochs, key=lambda row: row["validation"])
        if checkpoint["best_epoch"] != best["epoch"]:
            raise ValueError("Checkpoint not selected by inner validation")
        x = torch.from_numpy(segment_inputs(normalized[split["held"]]))
        model = SegmentReturnModel(x.shape[-1])
        model.load_state_dict(checkpoint["model"])
        model.eval()
        with torch.no_grad():
            predicted = model(x, torch.ones(len(held), 20)).numpy()
        predicted = predicted.astype(np.float64) * stats["target_std"]
        predicted += stats["target_mean"]
        expected = attributed["predictions"][split["held"]]
        # Different BLAS/Torch versions and batch sizes can round differently.
        np.testing.assert_allclose(predicted, expected, rtol=1e-5, atol=0.02)
        prediction_errors.extend(np.abs(predicted - expected).tolist())
        for index in split["held"]:
            if diagnostics[index]["fold"] != split["fold"]:
                raise ValueError("Attribution uses an in-sample fold")
            if diagnostics[index]["attribution_seed"] != (
                    protocol["attribution"]["attribution_seed_base"] + index):
                raise ValueError("Unexpected attribution seed")
            with np.load(directory / f"trajectory_{index:03d}.npz") as samples:
                contributions = samples["permutation_contributions"]
                permutations = samples["permutations"]
            rng = np.random.default_rng(diagnostics[index]["attribution_seed"])
            expected_order = np.stack([rng.permutation(20) for _ in range(128)])
            np.testing.assert_array_equal(permutations, expected_order)
            phi = contributions.mean(0)
            np.testing.assert_array_equal(phi, attributed["contributions"][index])
            rewards, _, _ = conserved_rewards(phi, returns[index])
            np.testing.assert_array_equal(rewards, attributed["rewards"][index])
            np.testing.assert_array_equal(rewards,
                                          redistributed["rewards"][starts[index]:
                                                                   ends[index] + 1])
        fold_reports.append(dict(fold=split["fold"], train=len(train),
                                  validation=len(valid), held=len(held),
                                  best_epoch=checkpoint["best_epoch"]))
    if sorted(seen) != list(range(len(returns))):
        raise ValueError("Outer folds do not attribute each trajectory exactly once")
    rounding = float(np.max(np.abs(returns - delayed_data["rewards"][ends])))
    conservation = float(np.max(np.abs(
        attributed["rewards"].astype(np.float64).sum(1) - returns)))
    report = dict(
        passed=True, trajectories=len(returns), folds=fold_reports,
        predictor_fields=["features", "returns", "starts", "ends"],
        predictor_features_exactly_states_and_actions=True,
        baseline_nonterminal_rewards_zero=True, matched_nonreward_fields=True,
        scientific_config_equal=True, all_attributions_use_held_fold=True,
        scalers_use_inner_training_only=True, all_saved_rewards_reconstructed=True,
        max_prediction_replay_difference=max(prediction_errors),
        max_total_vs_float32_terminal_difference=rounding,
        max_redistributed_return_error=conservation,
        limitations=["float64 totals differ from float32 terminal storage by rounding",
                     "undiscounted return conservation is not discounted invariance",
                     "additional predictor compute is not compute-matched",
                     "without uniform control, cannot isolate attribution benefit"])
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ["delayed", "campaign", "prepared", "fit", "output"]:
        parser.add_argument(f"--{name}", type=Path, required=True)
    parser.add_argument("--arm", choices=["medium", "medium_replay"], required=True)
    args = parser.parse_args()
    torch.set_num_threads(2)
    result = audit(args.delayed, args.campaign, args.prepared, args.fit, args.arm)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.output.exists():
        raise FileExistsError("Preserve previous audit receipts")
    write(args.output, result)
    print(result)
