"""Stop the four active 5090 seed-1 runs after their existing 500k save boundary."""

import argparse
import fcntl
import math
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

from scripts.cql_delayed.common import digest, read, verify, write

TARGET = 500000
CAMPAIGNS = [
    ("cql-corl-delayed-hc-seed1-5090-20261007", "medium", "cql_delayed"),
    ("cql-corl-delayed-hc-seed1-5090-20261007", "medium_replay", "cql_delayed"),
    ("cql-shapley-hcmr-v1-seed1-5090-20261007", "shapley", "cql_shapley"),
    ("cql-shapley-hcm-v1-seed1-5090-20261007", "shapley", "cql_shapley"),
]


def identity(pid):
    """Bind signals to a live process, its command, and this host boot."""
    directory = Path(f"/proc/{pid}")
    try:
        fields = (directory / "stat").read_text().rsplit(")", 1)[1].split()
        command = (directory / "cmdline").read_bytes().rstrip(b"\0").split(b"\0")
        if fields[0] == "Z" or not command[0]:
            return None
        return dict(pid=int(pid), start_ticks=fields[19],
                    boot_id=Path("/proc/sys/kernel/random/boot_id").read_text().strip(),
                    argv=[value.decode() for value in command])
    except (FileNotFoundError, ProcessLookupError, PermissionError):
        return None


def find_process(arguments):
    matches = []
    for path in Path("/proc").iterdir():
        if path.name.isdigit():
            found = identity(int(path.name))
            if found and found["argv"][1:] == arguments:
                matches.append(found)
    if len(matches) != 1:
        raise ValueError(f"Expected exactly one live process: {arguments}: {matches}")
    return matches[0]


def send(expected, signum):
    # The pidfd prevents PID reuse between the identity check and the signal.
    try:
        descriptor = os.pidfd_open(expected["pid"])
    except ProcessLookupError:
        return False
    try:
        if identity(expected["pid"]) != expected:
            return False
        signal.pidfd_send_signal(descriptor, signum)
        return True
    except ProcessLookupError:
        return False
    finally:
        os.close(descriptor)


def terminate(expected, first=signal.SIGTERM, grace=15):
    for signum in dict.fromkeys([first, signal.SIGTERM, signal.SIGKILL]):
        if not send(expected, signum):
            return
        deadline = time.monotonic() + grace
        while time.monotonic() < deadline:
            if identity(expected["pid"]) != expected:
                return
            time.sleep(0.1)
    raise RuntimeError(f"Process did not exit: {expected['pid']}")


def prepare(project, directory):
    if not hasattr(os, "pidfd_open") or not hasattr(signal, "pidfd_send_signal"):
        raise RuntimeError("Use the 5090 Python runtime with Linux pidfd support")
    jobs = []
    for campaign, arm, runner in CAMPAIGNS:
        root = project / "results" / campaign
        p = verify(root)
        spec = p["runs"][arm]
        local = read(root / arm / "training/status.json")
        if (spec["seed"] != 1 or spec["updates"] != 1000000
                or spec["eval_every"] != 5000 or spec["eval_episodes"] != 10
                or local["status"] != "training"
                or local["completed_updates"] >= TARGET):
            raise ValueError(f"Not an eligible active seed-1 run: {root}/{arm}")
        train = find_process([str(root / "source/scripts" / runner / "train.py"),
                              "--root", str(root), "--arm", arm])
        observer = find_process(["-m", "scripts.cql_5090.observe",
                                 "--root", str(root), "--arm", arm])
        jobs.append(dict(root=str(root), arm=arm, spec=spec, train=train,
                         observer=observer, original_status=local,
                         protocol_sha256=digest(root / "protocol.json")))
    directory.mkdir(parents=True, exist_ok=False)
    write(directory / "plan.json", dict(
        target_updates=TARGET, created_unix=time.time(), jobs=jobs,
        reason="User requested that currently running experiments stop at 500k",
        queued_experiments="Unchanged: 14 runs at 100k; GPU slots release on exit"))


def evaluation(path, target, episodes):
    row = read(path)
    if (row["completed_updates"] != target or len(row["episodes"]) != episodes
            or not all(math.isfinite(float(value)) for value in
                       [row["normalized_score"], row["raw_return_mean"],
                        *row["episodes"]])):
        raise ValueError(f"Incomplete or nonfinite evaluation: {path}")
    return row


def checkpoint(path, target):
    import torch

    # Only load checkpoints generated by these trusted local training processes.
    saved = torch.load(path, map_location="cpu", weights_only=False)
    required = {"trainer", "state_mean", "state_std", "completed_updates",
                "numpy_rng", "python_rng", "torch_rng", "cuda_rng"}
    trainer_keys = {"actor", "critic1", "critic2", "critic1_target", "critic2_target",
                    "critic_1_optimizer", "critic_2_optimizer", "actor_optim",
                    "sac_log_alpha", "sac_log_alpha_optim", "cql_log_alpha",
                    "cql_log_alpha_optim", "total_it"}
    if (not required.issubset(saved) or saved["completed_updates"] != target
            or not trainer_keys.issubset(saved["trainer"])
            or saved["trainer"].get("total_it") != target):
        raise ValueError("Checkpoint is incomplete or belongs to another update")


def bounded_rows(work, target):
    """Replay exact local telemetry, preserving raw history beyond the cutoff."""
    from scripts.cql_5090.observe import collect

    return {step: values for step, values in collect(
        work, dict(updates=0, evaluations=[])).items() if step <= target}


def result_summary(work, target, spec):
    rows = [evaluation(work / f"eval_{step:07d}.json", step, spec["eval_episodes"])
            for step in range(spec["eval_every"], target + 1, spec["eval_every"])]
    scores = [row["normalized_score"] for row in rows]
    return {"result/final_normalized_score": scores[-1],
            "result/best_normalized_score": max(scores),
            "result/last10_mean": sum(scores[-10:]) / len(scores[-10:]),
            "result/best_updates": rows[scores.index(max(scores))]["completed_updates"],
            "completed_updates": target, "effective_max_timesteps": target,
            "original_max_timesteps": spec["updates"],
            "status": "stopped_by_user", "stop_reason": "User requested 500k budget"}


def finish_wandb(job, spool, target):
    import wandb

    root, arm = Path(job["root"]), job["arm"]
    work = root / arm / "training"
    spec = job["spec"]
    protocol = read(root / "protocol.json")
    receipt = read(spool / "stop_receipt.json")
    summary = result_summary(work, target, spec)
    summary.update({"stop/last_recorded_updates": receipt["last_recorded_updates"],
                    "stop/discarded_tail": receipt["tail_note"],
                    "stop/checkpoint_sha256": receipt["checkpoint_sha256"]})
    final_name = spec["wandb_name"].replace("-1M-", "-500k-")
    # Hold the historical observer's lock as well: only one W&B writer per run.
    with (root / "wandb_sync" / arm / "lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        run = wandb.init(
            entity=protocol["wandb_entity"], project=protocol["wandb_project"],
            id=spec["wandb_id"], name=final_name, resume="must", mode="online",
            dir=str(spool), settings=wandb.Settings(init_timeout=60, console="off"))
        try:
            run.name = final_name
            run.config.update(dict(updates=target, effective_max_timesteps=target,
                                   original_max_timesteps=spec["updates"],
                                   wandb_name=final_name,
                                   original_wandb_name=spec["wandb_name"],
                                   budget_change="User requested 500k stop"),
                              allow_val_change=True)
            run.define_metric("completed_updates")
            run.define_metric("*", step_metric="completed_updates")
            # Old cursors precede asynchronous uploads. A bounded replay guarantees
            # the last evaluation arrives even after an observer/network failure.
            # It may duplicate identical historical rows; mark them explicitly.
            for step, values in sorted(bounded_rows(work, target).items()):
                run.log(dict(completed_updates=step, **values,
                             stop500k_replay=True))
            run.save(str(work / f"checkpoint_{target:07d}.pt"),
                     base_path=str(root), policy="now")
            run.save(str(spool / "stop_receipt.json"),
                     base_path=str(spool), policy="now")
            run.summary.update(summary)
        except BaseException:
            run.finish(exit_code=1)
            raise
        run.finish()
        remote = wandb.Api(timeout=40).run(
            f"{protocol['wandb_entity']}/{protocol['wandb_project']}/{spec['wandb_id']}")
        if (remote.state != "finished" or remote.name != final_name
                or remote.summary.get("completed_updates") != target
                or not math.isclose(remote.summary["result/final_normalized_score"],
                                    summary["result/final_normalized_score"])):
            raise ValueError("W&B 500k finalization readback differs")
        if remote.file(f"{arm}/training/checkpoint_{target:07d}.pt").size <= 0:
            raise ValueError("W&B checkpoint upload missing")
        write(spool / "wandb_verified.json", dict(
            verified=True, name=remote.name, id=remote.id, url=remote.url,
            summary=summary, verified_unix=time.time()))


def watch(plan_path, index):
    import torch

    torch.set_num_threads(1)
    plan = read(plan_path)
    job, target = plan["jobs"][index], plan["target_updates"]
    root, arm = Path(job["root"]), job["arm"]
    work = root / arm / "training"
    spool = plan_path.parent / f"run{index}"
    spool.mkdir(exist_ok=True)

    def status(stage, **extra):
        write(spool / "status.json", dict(stage=stage, pid=os.getpid(),
                                          updated_unix=time.time(), **extra))

    with (spool / "lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        try:
            if digest(root / "protocol.json") != job["protocol_sha256"]:
                raise ValueError("Historical protocol changed after guard preparation")
            verify(root)
            receipt_path = spool / "stop_receipt.json"
            if not receipt_path.exists():
                while True:
                    local = read(work / "status.json")
                    status("armed", training=local, target_updates=target)
                    ready = False
                    if local["completed_updates"] >= target:
                        try:
                            evaluation(work / f"eval_{target:07d}.json", target,
                                       job["spec"]["eval_episodes"])
                            checkpoint(work / f"checkpoint_{target:07d}.pt", target)
                            ready = True
                        except Exception as error:
                            status("waiting_for_complete_500k_save", error=repr(error))
                    if ready:
                        # Durable intent before the signal makes interrupted stop
                        # attempts recoverable without touching another process.
                        intent = spool / "stop_intent.json"
                        if not intent.exists():
                            write(intent, dict(training=local, unix=time.time()))
                        terminate(job["train"])
                        last = read(work / "status.json")
                        saved = work / f"checkpoint_{target:07d}.pt"
                        write(receipt_path, dict(
                            target_updates=target,
                            original_updates=job["spec"]["updates"],
                            original_status=read(intent)["training"],
                            last_training_status=last,
                            last_recorded_updates=last["completed_updates"],
                            checkpoint=str(saved), checkpoint_sha256=digest(saved),
                            stopped_unix=time.time(), train_identity=job["train"],
                            reason=plan["reason"],
                            tail_note="The selected checkpoint/evaluation is exactly "
                            "500k. Additional unsaved updates before termination are "
                            "discarded; the last status is only a 100-update lower "
                            "bound on physical progress. Raw logs are retained."))
                        break
                    if identity(job["train"]["pid"]) != job["train"]:
                        raise RuntimeError("Training exited before a valid 500k save")
                    time.sleep(0.2 if local["completed_updates"] >= target - 100 else 2)
            # Kill no managers or process groups; queues count GPU PIDs directly.
            terminate(job["observer"], first=signal.SIGINT)
            receipt = read(receipt_path)
            summary = result_summary(work, target, job["spec"])
            local = dict(status="stopped_by_user", completed_updates=target,
                         final_normalized_score=summary["result/final_normalized_score"],
                         original_max_timesteps=job["spec"]["updates"],
                         effective_max_timesteps=target, stop_receipt=str(receipt_path),
                         last_recorded_updates=receipt["last_recorded_updates"])
            write(work / "status.json", local)
            write(work / "user_stop_500k.json", receipt)
            while not (spool / "wandb_verified.json").exists():
                status("training_stopped_wandb_finalizing", training=local)
                try:
                    finish_wandb(job, spool, target)
                except Exception as error:
                    status("training_stopped_wandb_retry", error=repr(error))
                    time.sleep(30)
            status("completed", training=local)
        except BaseException as error:
            status("needs_attention", error=repr(error))
            raise


def launch(plan_path):
    plan = read(plan_path)
    with (plan_path.parent / "launch.lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        children = []
        for index in range(len(plan["jobs"])):
            with (plan_path.parent / f"run{index}.log").open("a") as stream:
                children.append(subprocess.Popen([
                    sys.executable, "-m", "scripts.cql_stop_500k.run", "watch",
                    "--plan", str(plan_path), "--index", str(index)],
                    stdout=stream, stderr=subprocess.STDOUT, start_new_session=True))
        while any(child.poll() is None for child in children):
            write(plan_path.parent / "supervisor.json", dict(
                pid=os.getpid(), updated_unix=time.time(),
                children=[dict(pid=child.pid, exit=child.poll()) for child in children]))
            time.sleep(5)
        if any(child.returncode for child in children):
            raise RuntimeError("A stop guard needs attention; inspect run*/status.json")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["prepare", "launch", "watch"])
    parser.add_argument("--project", type=Path)
    parser.add_argument("--directory", type=Path)
    parser.add_argument("--plan", type=Path)
    parser.add_argument("--index", type=int)
    args = parser.parse_args()
    if args.action == "prepare":
        prepare(args.project.resolve(), args.directory.resolve())
    elif args.action == "launch":
        launch(args.plan.resolve())
    else:
        watch(args.plan.resolve(), args.index)
